// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnD6UIpPtcxUfX4EdTKdTW5NW7KwQITY',
    appId: '1:488951056516:web:de45bfa8acb31c737d5ad1',
    messagingSenderId: '488951056516',
    projectId: 'cw06-6434d',
    authDomain: 'cw06-6434d.firebaseapp.com',
    storageBucket: 'cw06-6434d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVALW1d16HkcZuoyrWUM-eZx3k2DnUT0',
    appId: '1:488951056516:android:96817031ac4197647d5ad1',
    messagingSenderId: '488951056516',
    projectId: 'cw06-6434d',
    storageBucket: 'cw06-6434d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqSMsX3bh6a1v3JWbRxFhAIxfONJX8tQ',
    appId: '1:488951056516:ios:11e2fab0112799017d5ad1',
    messagingSenderId: '488951056516',
    projectId: 'cw06-6434d',
    storageBucket: 'cw06-6434d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqSMsX3bh6a1v3JWbRxFhAIxfONJX8tQ',
    appId: '1:488951056516:ios:11e2fab0112799017d5ad1',
    messagingSenderId: '488951056516',
    projectId: 'cw06-6434d',
    storageBucket: 'cw06-6434d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudOperations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQnD6UIpPtcxUfX4EdTKdTW5NW7KwQITY',
    appId: '1:488951056516:web:7267ecfcbdf137817d5ad1',
    messagingSenderId: '488951056516',
    projectId: 'cw06-6434d',
    authDomain: 'cw06-6434d.firebaseapp.com',
    storageBucket: 'cw06-6434d.firebasestorage.app',
  );
}
